Display data modal
technojam/technojam-frontend pull request #258
Opened 2020-10-01 22:21 UTC by kala2

2020-10-02 06:05 UTC, lakshya-20 requested changes
Hey, update the editEvent function to pass the event detail to modal.

2020-10-02 09:02 UTC, Isha2103 approved these changes

2020-10-02 09:05 UTC, Isha2103 approved these changes

2020-10-02 11:08 UTC, lakshya-20 approved these changes

2020-10-02 11:08 UTC, merged

2020-10-02 11:09 UTC, lakshya-20 commented
Thanks! @kala2 :)

2020-10-12 09:43 UTC, kala2 commented
Could you please add the hacktoberfest-accepted label? It's for the hacktoberfest event!