Added reset password feature
technojam/technojam-frontend pull request #282
Opened 2020-11-24 13:22 UTC by lakshya-20

- Added reset password function in context API
- Added reset password UI part
**Error handling needs to be improved**

2020-11-24 15:16 UTC, Ritwik880 approved these changes

2020-11-24 16:05 UTC, Isha2103 requested changes
Topmenu.js line no. 581 										
<p style={{float:"left" }}>Dont't have an account?</p>
Grammatical Error- Don't

2020-11-26 14:33 UTC, mohdorusaid approved these changes

2020-11-28 17:58 UTC, sakshi172015 approved these changes

2020-12-07 21:27 UTC, codebloded approved these changes

2021-03-12 03:29 UTC, merged